// vue/calculator/src/main/Calculator.vue
<template>
    <div class="calculator">
        <Display value=""/>
        <Button label="AC" triple/>
        <Button label="/" operation/>
        <Button label="7"/>
        <Button label="8"/>
        <Button label="9"/>
        <Button label="*" operation/>
        <Button label="4"/>
        <Button label="5"/>
        <Button label="6"/>
        <Button label="-" operation/>
        <Button label="1"/>
        <Button label="2"/>
        <Button label="3"/>
        <Button label="+" operation/>
        <Button label="0" double/>
        <Button label="."/>
        <Button label="=" operation/>
    </div>
</template>

<script>
import Display from '../components/Display.vue'
import Button from '../components/Button.vue'
export default {
    components: {Button, Display}
}
</script>

<style>
    .calculator{
        height: 320px;
        width: 235px;
        border-radius: 5px;
        display: grid;
        grid-template-columns: repeat(4, 25%);
        grid-template-rows: 1fr 48px 48px 48px 48px 48px;
    }
</style>

// React/calculadora/src/main/Calculator.jsx
import React, {Component} from "react"
import './Calculator.css'
import Button from '../components/Button'
import Display from '../components/Display'

export default class Calculator extends Component {
    constructor(props){
        super(props)
        this.clearMemory = this.clearMemory.bind(this)
        this.setOperation = this.setOperation.bind(this)
        this.addDigit = this.addDigit.bind(this)
    }
    clearMemory(){
        console.log('Limpar')
    }
    setOperation(operation){
        console.log(operation)
    }
    addDigit(n){
        console.log(n)
    }
    render(){
        
        return (
            <div className="calculator">
                <Display value={100}/>
                <Button label="AC" click = {this.clearMemory} triple/>
                <Button label="/" click={this.setOperation} operation double/>
                <Button label="7" click={this.addDigit}/>
                <Button label="8" click={this.addDigit}/>
                <Button label="9" click={this.addDigit}/>
                <Button label="*" click={this.setOperation} operation double/>
                <Button label="4" click={this.addDigit}/>
                <Button label="5" click={this.addDigit}/>
                <Button label="6" click={this.addDigit}/>
                <Button label="-" click={this.setOperation} operation double/>
                <Button label="1" click={this.addDigit}/>
                <Button label="2" click={this.addDigit}/>
                <Button label="3" click={this.addDigit}/>
                <Button label="+" click={this.setOperation} operation double/>
                <Button label="0" click={this.addDigit} double/>
                <Button label="." click={this.addDigit}/>
                <Button label="=" click={this.setOperation} operation />
            </div>
        )
    }
}
